apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentaisl-external-secret
  namespace: user-monitoring-grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: user-monitoring-grafana-username
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: user-monitoring-grafana-password