apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: user-monitoring-grafana
  labels:
    dashboards: user-monitoring-grafana
    folders: user-monitoring-grafana
  namespace: user-monitoring-grafana
spec:
  route:
    spec: {}
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-credentials