apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloud-dns-credentials
  namespace: letsencrypt-job
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: cloud-dns-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-secret-access-key