apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: oauth-github-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: github-client-secret