apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github 
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: 8276d396a85c69a93e35
      clientSecret: 
        name: oauth-github-client-secret
      organizations: 
      - joranbergfeld-org