apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: file-local-storage
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ocp1
              - ocp2
              - ocp3
              - ocp4
  storageClassDevices:
    - devicePaths:
        - /dev/sda
      fsType: ext4
      storageClassName: file-local-storage
      volumeMode: Filesystem